openapi: 3.0.0
info:

  title: Documentation For GroomerShop- OpenAPI 3.0

  description: |
    ## Technologies

    - Spring Boot: Framework for building Java applications.

  version: 1.0.0

paths:

  /send:
    post:
      summary: Send Email
      description: This endpoint is responsible for sending emails in one go.

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotificationDTO'

      responses:

        '200':
          description: Success Status
          content:
            text/plain:
              schema:
                type: string
              example: Sending Emails ...

        '400':
          description: Exception Status with message.
          content:
            text/plain:
              schema:
                type: string
              example: |
                Exception while sending email: {error here}

components:
  schemas:
    EmailNotificationDTO:
      type: object
      properties:

        recipient:
          type: string
          description: Email recipient

        subject:
          type: string
          description: Email subject

        body:
          type: string
          description: Email body